### ISSUE TITLE
An exception has occurred

### ISSUE THREAD

**Issue by d3adpan** [multimokia/MAS-Submod-Enhanced-Idle#1]
[traceback.txt](https://github.com/multimokia/MAS-Submod-Enhanced-Idle/files/4934670/traceback.txt)

Ignoring the error seems to have no ill effects.  Single monitor setup.

**Comment by multimokia** [comment]
Outside this instance, has it worked?

**Comment by d3adpan** [comment]
So far it has crashed twice in a relatively short period of time, less than an hour.  Both times I was in a Firefox window with MAS in the background but not minimised.  And yep, it is working just fine both before and after a crash - love this new addition!

**Comment by zombiepigdragon** [comment]
This occurs with on my system as well. It seems xdotool sometimes fails for no particular reason, which can be reproduced by entering `while xdotool search --name 'Monika After Story' > /dev/null; do :; done` into a shell. After some amount of time (ranged from 10 seconds to about 20 minutes in my testing) this will exit with an error along the lines of
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0xe572c7
  Serial number of failed request:  316
  Current serial number in output stream:  316
```
I think just reusing the last successful result when the call to xdotool throws a CalledProcessError in `getMASWindowID()` should work around the issue.

**Comment by multimokia** [comment]
Noted, I've prepped a test script and sent over to @d3adpan. Basically a wrapper try/except function around it. Given that result though. I wonder if it will just straight up stop responding to cursor position entirely until a MAS restart, or if it'll just pick it up again later.

Feel free to grab the source from the master branch to test yourself if you wish.

**Comment by multimokia** [comment]
@d3adpan any issues in the new rpy?

**Comment by zombiepigdragon** [comment]
@multimokia It works perfectly, at least for me. I have 67 lines in my `mas_log.txt` mentioning "Failed to check output" but everything works normally.

**Comment by multimokia** [comment]
Great. While it's kinda pain that it happens, at least the crashes are fixed. I'll release the update then

**Comment by multimokia** [comment]
Closing as resolved.
