### ISSUE TITLE
[Suggestion] Auto remove Enhanced Idle?

### ISSUE THREAD

**Issue by AdeenDragon** [multimokia/MAS-Submod-Enhanced-Idle#3]
Would it be possible for the Submod Updater to remove/disable Enhanced Idle?

It appears that there's a lot of people who didn't realize that Enhanced Idle is part of 0.12.0 of MAS; if the Submod Updater removed the submod version, it should reduce support requests.

This would frustrate people who still use 0.11.x, unless the Submod Updater could tell the difference between 0.12.0 and 0.11.x, and only remove Enhanced Idle for people who use 0.12.0

**Comment by multimokia** [comment]
I actually added update scripts in main MAS to remove the submod, however it's not a guaranteed removal seeing as its location may not be exactly in the right place.

It should, however, be enough to remove it for most users.
